name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'v0.0.1'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Compile extension
        run: npm run compile

      - name: Package extension
        run: vsce package

      - name: Get version from package.json
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${{ github.ref_name || github.event.inputs.version }}"
          RELEASE_NAME="$TAG_NAME"
          RELEASE_BODY="Release $TAG_NAME of Zeal 8-bit Emulator Preview VS Code Extension

          ## Changes
          - See commit history for detailed changes

          ## Installation
          Download the \`.vsix\` file and install it in VS Code using:
          - Command Palette: \`Extensions: Install from VSIX...\`
          - Or drag and drop the file into the Extensions view"

          gh release create "$TAG_NAME" \
            --title "$RELEASE_NAME" \
            --notes "$RELEASE_BODY" \
            --draft \
            ./zeal8bit-${{ steps.package-version.outputs.version }}.vsix
